#!/usr/bin/env python3
"""Deterministic renderer for the Doggiehood daily pipeline dashboard (#193).

Two responsibilities, cleanly split so the render is testable without network:

  * ``render_body(state)`` — PURE. Turns a state dict into the exact markdown
    body of issue #193. Golden-tested; no GitHub I/O.
  * ``fetch_state(repo, token)`` — queries the GitHub REST API (stdlib urllib,
    no third-party deps) and assembles the state dict.

Entry points:
  * ``render_dashboard.py --render-only``  reads a state JSON on stdin and
    prints the body (used by tests and for local preview).
  * ``render_dashboard.py``                fetches live state and prints the
    body.
  * ``render_dashboard.py --write``        fetches, renders, and PATCHes #193.

Auth: uses ``GITHUB_TOKEN`` from the environment (the token GitHub Actions
injects), so the whole thing runs headless in the scheduled workflow with no
LLM in the loop. See docs/engineering/issue-pipeline.md.
"""

import json
import os
import sys
import urllib.error
import urllib.request

REPO_DEFAULT = "derekwinters/lucas-doggiehood"
DASHBOARD_ISSUE = 193
API = "https://api.github.com"

# Focus-milestone pie colors — four coarse stages (#402): Unplanned, In
# Planning, Ready, Done. Every focus-milestone issue maps to exactly one slice
# so none can silently vanish from the total (#265 invariant, preserved).
# Colors are reused from the retired 7-slice palette rather than invented.
PIE_DONE = "#3fae5a"           # green  (closed)
PIE_READY = "#e6c200"          # yellow (ready-for-work + in-progress)
PIE_IN_PLANNING = "#e6862e"    # orange (ai-triage + pending + clarification)
PIE_UNPLANNED = "#8a8a8a"      # gray   (parked + no pipeline-state label)

BAR_CELLS = 10  # width of the ▰▱ progress bars in "Other milestones"

# Default nightly build cap (#240) when neither an override nor the #193
# marker supplies one — matches select_queue.py's own `cap = data.get("cap",
# 3)` fallback, so the two never drift.
DEFAULT_CAP = 3


def _issue_link(repo, number):
    return "[#%d](https://github.com/%s/issues/%d)" % (number, repo, number)


def _pr_link(repo, number):
    return "[#%d](https://github.com/%s/pull/%d)" % (number, repo, number)


def _progress_bar(done, total):
    if total <= 0:
        filled = 0
    else:
        filled = round(done / total * BAR_CELLS)
    filled = max(0, min(BAR_CELLS, filled))
    return "▰" * filled + "▱" * (BAR_CELLS - filled)


def compute_unblockers(graph):
    """Map each unblocking issue to the sorted open issues it unblocks (#250).

    ``graph`` is a list of ``{"number": int, "blocked_by": [int, ...]}`` for the
    OPEN issues only; ``blocked_by`` holds the hard blockers — the structured
    ``Blocked by: #N`` text lines UNIONED with native GitHub issue-dependency
    relationships (``_merged_blocked_by``, #321). Reads the same merged blocker
    graph the nightly builder / reconcile use — never prose.

    An **unblocking issue** is one that is open, is **not itself blocked** by any
    open issue, and appears in at least one other open issue's ``blocked_by``
    set. Returns ``{number: [sorted dependents]}`` containing only those
    unblockers; blocked issues and fully-independent issues are absent.
    """
    open_nums = {g["number"] for g in graph}
    blocked = {}
    unblocks = {}
    for g in graph:
        n = g["number"]
        open_blockers = [b for b in g.get("blocked_by", []) if b in open_nums]
        blocked[n] = bool(open_blockers)
        for b in open_blockers:
            unblocks.setdefault(b, set()).add(n)
    return {n: sorted(deps) for n, deps in unblocks.items()
            if not blocked.get(n)}


def render_body(state):
    repo = state.get("repo", REPO_DEFAULT)
    focus = state["focus"]
    fm = focus["milestone"]
    done = focus["done"]
    ready = focus["ready"]
    in_planning = focus["in_planning"]
    unplanned = focus["unplanned"]
    total = done + ready + in_planning + unplanned
    ym = state["your_move"]
    cap = state.get("cap", DEFAULT_CAP)

    L = []
    a = L.append

    # Hidden focus marker — the single source of truth read by the gatekeeper
    # and pipeline-dev. MUST be the first line. The hidden cap marker (#240)
    # follows immediately, same treatment: emitted on every render so the
    # nightly build cap is never lost.
    a("<!-- pipeline-focus: %s -->" % fm)
    a("<!-- pipeline-cap: %d -->" % cap)
    a("")
    a("_Auto-generated by the dashboard workflow — do not edit by hand; "
      "it is rewritten on a schedule and never closed._")
    a("")
    a("**As of:** %s · **Focus milestone:** `%s`" % (state["as_of"], fm))
    a("")

    # --- Focus milestone -------------------------------------------------
    a("## 🎯 Focus milestone — `%s`" % fm)
    a("**%d / %d complete**" % (done, total))
    a("")
    a("```mermaid")
    # Legend reads left-to-right through the stages: Unplanned → In Planning
    # → Ready → Done (#402). pie1..pie4 color the slices in that same order.
    a('%%{init: {"themeVariables": {"pie1": "' + PIE_UNPLANNED
      + '", "pie2": "' + PIE_IN_PLANNING
      + '", "pie3": "' + PIE_READY
      + '", "pie4": "' + PIE_DONE + '"}}}%%')
    a("pie showData title %s" % fm)
    a('    "Unplanned" : %d' % unplanned)
    a('    "In Planning" : %d' % in_planning)
    a('    "Ready" : %d' % ready)
    a('    "Done" : %d' % done)
    a("```")
    a("")
    a("**▶️ Ready-for-work queue** _(this milestone only, in nightly build order)_")
    a("")
    a("Nightly build cap: **%d**" % cap)
    a("")
    queue = focus.get("queue", [])
    if queue:
        a("| Issue | Title | Milestone | |")
        a("| - | - | - | - |")
        for it in queue:
            if it.get("blocked"):
                flag = " ⛔ _blocked_"
            elif it.get("unblocks"):
                # Highest-leverage pick: mark it and list the open issues it
                # unblocks (#250). By definition an unblocker is never blocked,
                # so ⭐ and ⛔ are mutually exclusive.
                deps = ", ".join(_issue_link(repo, n) for n in it["unblocks"])
                flag = " ⭐ unblocks %s" % deps
            else:
                flag = ""
            # Milestone is the focus milestone for every queued item (#336) —
            # shown for consistency with the other issue tables.
            a("| %s | %s | %s |%s |" % (_issue_link(repo, it["number"]),
                                        it["title"], it.get("milestone") or "",
                                        flag))
    else:
        a("_Nothing queued yet. `/approve` an analysis into this milestone and "
          "it lands here, blockers first. Set the active milestone anytime with "
          "`/focus <milestone>`._")
    a("")
    a("---")
    a("")

    # --- Your move -------------------------------------------------------
    a("### 🔔 Your move")
    a("| Queue | Count |")
    a("| - | - |")
    a("| 🔀 PRs awaiting your merge | **%d** |" % ym["prs"])
    a("| 🆕 New ideas to `/admit` | **%d** |" % ym["new_ideas"])
    a("| ✅ Analyses to `/approve` | **%d** |" % ym["approvals"])
    a("| ❓ Questions to answer | **%d** |" % ym["questions"])
    a("")
    a("---")
    a("")

    # --- Pull requests ---------------------------------------------------
    a("## 🔀 Pull requests")
    a("")
    awaiting = state["prs"].get("awaiting", [])
    if awaiting:
        a("**Awaiting your merge:**")
        a("")
        a("| PR | Title | State |")
        a("| - | - | - |")
        for pr in awaiting:
            a("| %s | `%s` | %s |"
              % (_pr_link(repo, pr["number"]), pr["title"], pr.get("state", "")))
    else:
        a("**Awaiting your merge:** _none right now._")
    a("")
    automation = state["prs"].get("automation", [])
    if automation:
        a("**Automation (separate cadence):**")
        a("")
        a("| PR | Title | State |")
        a("| - | - | - |")
        for pr in automation:
            a("| %s | `%s` | %s |"
              % (_pr_link(repo, pr["number"]), pr["title"], pr.get("state", "")))
        a("")
    a("---")
    a("")

    # --- New ideas (intake) ----------------------------------------------
    a("## 🆕 New ideas — awaiting your call")
    a("_Raw, ungated issues. `/admit` pulls one into analysis · `/park` hides it._")
    a("")
    _issue_table(a, repo, state.get("intake", []), show_blocked_by=True)
    a("")
    a("> **Your move:** `/admit` · `/park`")
    a("")
    a("---")
    a("")

    # --- Pending approval ------------------------------------------------
    a("## ✅ Pending approval — analysis done, awaiting you")
    a("_AI has triaged these; read the analysis on each, then act._")
    a("")
    _issue_table(a, repo, state.get("pending_approval", []), show_blocked_by=True)
    a("")
    a("> **Your move:** `/approve` (→ ready-for-work; milestone already set "
      "by analysis) · `/revise <notes>` · `/redo` · `/park`")
    a("")
    a("---")
    a("")

    # --- Needs clarification ---------------------------------------------
    a("## ❓ Needs clarification — blocked on your answer")
    a("_A specific question is posted on each issue — open it to read and reply._")
    a("")
    _issue_table(a, repo, state.get("needs_clarification", []), show_blocked_by=True)
    a("")
    a("> **Your move:** `/revise <notes>` · `/redo` · `/propose` · `/park`")
    a("")
    a("---")
    a("")

    # --- Parked ----------------------------------------------------------
    # Read-only listing so parked work stays visible (#249). Parked issues are
    # excluded from every active queue and count above; this is a reference
    # section, not a re-admission, so there is no "Your move" menu.
    a("## ⏸️ Parked")
    a("_Hidden from the pipeline and every active queue above. `/unpark` brings "
      "one back into intake._")
    a("")
    _issue_table(a, repo, state.get("parked", []))
    a("")
    a("---")
    a("")

    # --- Reconcile -------------------------------------------------------
    _reconcile_section(a, repo, state.get("reconcile") or {})

    # --- Other milestones ------------------------------------------------
    a("## 📦 Other milestones")
    a("_Live counts for every milestone outside the current focus._")
    a("")
    a("| Milestone | Progress | |")
    a("| - | - | - |")
    for m in state.get("other_milestones", []):
        if m.get("closed"):
            # Closed milestones are 100% done; they only clutter (#214).
            continue
        mdone, mopen = m["done"], m["open"]
        mtotal = mdone + mopen
        bar = _progress_bar(mdone, mtotal)
        note = " · _post-MVP_" if m.get("post_mvp") else ""
        a("| `%s` | `%s` | %d/%d complete · %d open%s |"
          % (m["title"], bar, mdone, mtotal, mopen, note))
    a("")
    a("---")
    a("")

    # --- Open issues by milestone chart ----------------------------------
    obm = state.get("open_by_milestone")
    if obm and obm.get("values"):
        a("## 📈 Open issues by milestone")
        a("")
        a("```mermaid")
        a("xychart-beta")
        a('    title "Open issues by milestone"')
        a("    x-axis [%s]" % ", ".join(obm["labels"]))
        a('    y-axis "Open issues" 0 --> %d' % obm["ymax"])
        a("    bar [%s]" % ", ".join(str(v) for v in obm["values"]))
        a("```")
        a("")
        a("---")
        a("")

    # --- Command reference (static) --------------------------------------
    a("### 📖 Command reference")
    a("Comment on any issue (only Derek's commands are honored):")
    a("")
    a("| Command | Effect |")
    a("| - | - |")
    a("| `/admit` | Pull a raw idea into AI analysis |")
    a("| `/approve` | Accept the analysis → ready-for-work (milestone already set by analysis) |")
    a("| `/revise <notes>` | Send back to analysis with your feedback |")
    a("| `/redo` | Discard the analysis and start it over |")
    a("| `/propose` | Authorize AI to draft the missing design/wireframe as a proposal |")
    a("| `/park` / `/unpark` | Hide from the pipeline / bring it back |")
    a("| `/milestone <name>` | Override the milestone |")
    a("| `/focus <name>` | Set the active milestone for nightly development |")
    a("| `/cap <n>` | Set the nightly dev build cap (this dashboard issue only) |")
    a("")
    a("_`/focus` can be set from any issue **or from this dashboard issue** — "
      "the gatekeeper honors it here even though every other command is "
      "issue-scoped. Relocating this focus marker to a dedicated single-writer "
      "store (a control issue or a repo variable) is tracked as decision #8._")
    a("")
    a("_`/cap <n>` is honored **only on this dashboard issue** — a positive "
      "integer sets the nightly build cap; non-numeric or non-positive input "
      "is rejected and the cap is left unchanged._")

    return "\n".join(L) + "\n"


def _reconcile_section(a, repo, rec):
    """Read-only "⚠️ Reconcile" section — board state drifted from reality.

    Lists the *flag* findings from the reconciliation sweep (issue #246):
    merged-but-open issues to close, orphaned ready-for-work, prose-only
    dependency references, and triage loops the sweep has stopped auto-requeuing
    (issue #710). The safe auto-fixes (stale-label strips, requeues) are applied
    by the gatekeeper routine, not shown as pending here; their counts are noted
    so the sweep's activity is visible.
    """
    done = rec.get("flag_done", [])
    orphaned = rec.get("orphaned_ready", [])
    prose = rec.get("prose_dep", [])
    stuck = rec.get("stuck_triage", [])
    fixed = rec.get("auto_fixed") or {}

    a("## ⚠️ Reconcile — board drifted from reality")
    a("_Detected by the reconciliation sweep. Auto-fixes (stale-label strips, "
      "requeues) are applied by the gatekeeper; the items below need your call._")
    a("")

    if done:
        a("**🔀 Merged but still open** — the work is on `main`; close these "
          "(#211 auto-closes the clean cases once it lands):")
        a("")
        a("| Issue | Summary |")
        a("| - | - |")
        for it in done:
            a("| %s | %s |" % (_issue_link(repo, it["number"]), it["title"]))
        a("")
    if orphaned:
        a("**🏷️ Ready-for-work with no milestone** — set one so the builder can "
          "queue it:")
        a("")
        a("| Issue | Summary |")
        a("| - | - |")
        for it in orphaned:
            a("| %s | %s |" % (_issue_link(repo, it["number"]), it["title"]))
        a("")
    if prose:
        a("**🔗 Prose-only dependency references** — record as structured "
          "`Blocked by:` / `Depends on:` so the queue can order them:")
        a("")
        a("| Issue | Summary | References |")
        a("| - | - | - |")
        for it in prose:
            refs = ", ".join(_issue_link(repo, n) for n in it.get("refs", []))
            a("| %s | %s | %s |"
              % (_issue_link(repo, it["number"]), it["title"], refs))
        a("")
    if stuck:
        # Issue #710. The auto-requeue is bounded, and the bound has to be
        # visible: an invisible stop is the old silent churn with fewer
        # comments. Almost always the cause is a hand-back comment whose marker
        # the sweep's recognizer cannot see.
        a("**🔁 Triage stuck in a loop** — handed back repeatedly with no "
          "analysis the sweep can recognize; auto-requeue **stopped**, these "
          "need a look:")
        a("")
        a("| Issue | Summary | Stuck in | Hand-backs |")
        a("| - | - | - | - |")
        for it in stuck:
            a("| %s | %s | `%s` | %s |"
              % (_issue_link(repo, it["number"]), it["title"],
                 it.get("handback_state", ""), it.get("handbacks", "")))
        a("")
    if not (done or orphaned or prose or stuck):
        a("_✅ Nothing to reconcile — every issue's labels match reality._")
        a("")

    if fixed:
        strips = fixed.get("strip_labels", 0)
        requeues = fixed.get("requeue", 0)
        a("_Sweep auto-fixed this run: %d stale-label strip(s), %d requeue(s)._"
          % (strips, requeues))
        a("")
    a("---")
    a("")


def _issue_table(a, repo, issues, show_blocked_by=False):
    """Render an issue table.

    Every issue table carries a **Milestone** column (#336) listing the issue's
    milestone title, or an empty cell when it has none.

    When ``show_blocked_by`` is set (#241) a fourth **Blocked by** column lists
    each issue's structured ``Blocked by: #N`` hard blockers as links (empty
    cell when it has none), so every pipeline stage surfaces its blockers the
    same way the focus ready-for-work queue does. The Parked listing keeps the
    milestone-only three-column form.
    """
    if not issues:
        a("_None right now._")
        return
    if show_blocked_by:
        a("| Issue | Summary | Milestone | Blocked by |")
        a("| - | - | - | - |")
        for it in issues:
            blockers = ", ".join(_issue_link(repo, n)
                                 for n in it.get("blocked_by", []))
            a("| %s | %s | %s | %s |"
              % (_issue_link(repo, it["number"]), it["title"],
                 it.get("milestone") or "", blockers))
        return
    a("| Issue | Summary | Milestone |")
    a("| - | - | - |")
    for it in issues:
        a("| %s | %s | %s |"
          % (_issue_link(repo, it["number"]), it["title"],
             it.get("milestone") or ""))


# --------------------------------------------------------------------------
# Live-state fetch (GitHub REST API via stdlib urllib). Not exercised by the
# unit tests, which drive render_body() directly with a fixture.
# --------------------------------------------------------------------------

def _api_get(path, token):
    req = urllib.request.Request(API + path)
    req.add_header("Authorization", "Bearer %s" % token)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "doggiehood-dashboard")
    with urllib.request.urlopen(req) as resp:
        return json.load(resp)


def _paginate(path, token):
    items, page = [], 1
    sep = "&" if "?" in path else "?"
    while True:
        batch = _api_get("%s%sper_page=100&page=%d" % (path, sep, page), token)
        if not batch:
            break
        items.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return items


def _milestone_num(title):
    import re
    m = re.match(r"^0*(\d+)", title or "")
    return int(m.group(1)) if m else 9999


def _focus_bucket(lbl):
    """Classify one open focus-milestone issue's labels into a pie slice (#402).

    Four coarse stages, collapsing the seven pipeline states. Priority order
    (highest wins), matching the state table in
    docs/engineering/issue-pipeline.md:

      * ``parked``                                            → ``unplanned``
      * ``ready-for-work`` / ``in-progress``                  → ``ready``
      * ``ai-triage`` / ``pending-approval`` / ``needs-clarification``
                                                              → ``in_planning``
      * no pipeline-state label at all (e.g. a pre-`/admit`
        raw idea, the retired needs-triage fall-through)      → ``unplanned``

    Closed issues are tallied as ``done`` by the caller, outside this
    function. Every open, non-excluded focus-milestone issue maps to exactly
    one bucket so none can silently vanish from the pie total (#265).
    """
    if "parked" in lbl:
        return "unplanned"
    if "ready-for-work" in lbl or "in-progress" in lbl:
        return "ready"
    if lbl & {"ai-triage", "pending-approval", "needs-clarification"}:
        return "in_planning"
    return "unplanned"


def fetch_state(repo, token, as_of):
    raw = _paginate("/repos/%s/issues?state=all" % repo, token)
    issues = [i for i in raw if "pull_request" not in i]

    def labels_of(i):
        return {l["name"] for l in i.get("labels", [])}

    # Native GitHub issue-dependency hard blockers per OPEN issue (#321), read
    # from the dependencies API via reconcile's shared fetcher. Merged with the
    # text-line `Blocked by:` parse (`_merged_blocked_by`) everywhere a blocker
    # graph is built below, so the "Blocked by" columns and the unblocker graph
    # both see native relationships. Only open issues are fetched — closed ones
    # never appear in a blocker graph.
    native_bb = {i["number"]: _reconcile_mod().native_blocked_by(
                     repo, i["number"], token)
                 for i in issues if i["state"] == "open"}

    # Milestone roll-up.
    milestones = {}
    for i in issues:
        ms = i.get("milestone")
        if not ms:
            continue
        title = ms["title"]
        lbl = labels_of(i)
        if "dashboard" in lbl or "type:epic" in lbl or "parked" in lbl:
            continue
        b = milestones.setdefault(
            title, {"done": 0, "ready": 0, "remaining": 0, "closed": False})
        # A milestone the maintainer has closed on GitHub is 100% done and is
        # hidden from "Other milestones" and the chart (#214).
        b["closed"] = ms.get("state") == "closed"
        if i["state"] == "closed":
            b["done"] += 1
        elif "ready-for-work" in lbl:
            b["ready"] += 1
        else:
            b["remaining"] += 1

    # Focus precedence (#204/#234): DASHBOARD_SET_FOCUS override (a `/focus`
    # re-render) > #193 marker > lowest version milestone with ready work.
    dash = _api_get("/repos/%s/issues/%d" % (repo, DASHBOARD_ISSUE), token)
    ready_ms = [t for t, b in milestones.items() if b["ready"] > 0]
    pool = ready_ms or list(milestones)
    fallback = min(pool, key=_milestone_num) if pool else "(none)"
    focus_title = _resolve_focus(
        os.environ.get("DASHBOARD_SET_FOCUS"),
        _read_focus_marker(dash.get("body") or ""),
        fallback)
    # Focus-milestone pie tally: a dedicated 4-bucket pass (#402), separate from
    # the generic `milestones` roll-up above. Unlike that roll-up, this pass
    # *includes* `parked` issues — folding them into the Unplanned slice instead
    # of letting them vanish from the total (#265) — while still excluding
    # `dashboard`/`type:epic` bookkeeping issues.
    fb = {"done": 0, "ready": 0, "in_planning": 0, "unplanned": 0}
    for i in issues:
        ms = i.get("milestone")
        if not ms or ms["title"] != focus_title:
            continue
        lbl = labels_of(i)
        if "dashboard" in lbl or "type:epic" in lbl:
            continue
        if i["state"] == "closed":
            fb["done"] += 1
        else:
            fb[_focus_bucket(lbl)] += 1

    # Nightly build cap (#240): DASHBOARD_SET_CAP override (a `/cap`
    # re-render) > #193 marker > DEFAULT_CAP.
    cap = _resolve_cap(
        os.environ.get("DASHBOARD_SET_CAP"),
        _read_cap_marker(dash.get("body") or ""))

    def open_issues_with(label):
        out = []
        for i in issues:
            if i["state"] != "open":
                continue
            lbl = labels_of(i)
            if i["number"] == DASHBOARD_ISSUE or "parked" in lbl or "type:epic" in lbl:
                continue
            if label(lbl):
                out.append({"number": i["number"], "title": _clean(i["title"]),
                            "milestone": _milestone_title(i),
                            "blocked_by": _merged_blocked_by(
                                i.get("body") or "",
                                native_bb.get(i["number"], ()))})
        return out

    intake = open_issues_with(lambda l: not (l & {
        "ai-triage", "pending-approval", "needs-clarification",
        "ready-for-work", "in-progress"}))
    pending = open_issues_with(lambda l: "pending-approval" in l)
    needs = open_issues_with(lambda l: "needs-clarification" in l)

    # Parked: a separate read-only listing (#249). Not routed through
    # open_issues_with, which excludes parked issues by design; every active
    # queue/count stays parked-free while this surfaces them on their own.
    parked = []
    for i in issues:
        if i["state"] != "open":
            continue
        lbl = labels_of(i)
        if i["number"] == DASHBOARD_ISSUE or "type:epic" in lbl:
            continue
        if "parked" in lbl:
            parked.append({"number": i["number"], "title": _clean(i["title"]),
                           "milestone": _milestone_title(i)})

    # Unblocker graph over ALL open issues (#250): read the same structured
    # `Blocked by:` hard-blocker set the nightly builder / reconcile use, then
    # derive which open issues are unblockers (open, not blocked, block >=1 open
    # issue). The star is only ever *rendered* on the focus ready-for-work queue,
    # but the graph must span every open issue so a queue item's cross-milestone
    # dependents are counted.
    open_numbers = {i["number"] for i in issues if i["state"] == "open"}
    open_graph = [
        {"number": i["number"],
         "blocked_by": [b for b in _merged_blocked_by(
                            i.get("body") or "", native_bb.get(i["number"], ()))
                        if b in open_numbers]}
        for i in issues if i["state"] == "open"
    ]
    unblocker_map = compute_unblockers(open_graph)

    # Focus ready-for-work queue.
    queue = []
    for i in issues:
        lbl = labels_of(i)
        ms = i.get("milestone")
        if (i["state"] == "open" and "ready-for-work" in lbl
                and ms and ms["title"] == focus_title and "parked" not in lbl):
            blocked = any(b in open_numbers for b in _merged_blocked_by(
                i.get("body") or "", native_bb.get(i["number"], ())))
            queue.append({"number": i["number"], "title": _clean(i["title"]),
                          "milestone": _milestone_title(i),
                          "blocked": blocked,
                          "unblocks": unblocker_map.get(i["number"], [])})
    # Unblockers sort to the top (highest-leverage picks first), blocked issues
    # to the bottom, ties broken by issue number (#250).
    queue.sort(key=lambda q: (q["blocked"], not q["unblocks"], q["number"]))

    # Pull requests.
    pulls = _paginate("/repos/%s/pulls?state=open" % repo, token)
    awaiting, automation = [], []
    for p in pulls:
        title = p["title"]
        is_rp = (title.startswith("chore(main): release")
                 or p["head"]["ref"].startswith("release-please"))
        entry = {"number": p["number"], "title": title,
                 "state": "release-please — merge to cut the release" if is_rp
                 else "open"}
        (automation if is_rp else awaiting).append(entry)

    # Other-milestone summaries + open-by-milestone chart.
    other, chart_labels, chart_vals = [], [], []
    for title in sorted(milestones, key=_milestone_num):
        b = milestones[title]
        if b["closed"]:
            # Closed milestones clutter the report; drop from both (#214).
            continue
        opencount = b["ready"] + b["remaining"]
        if title != focus_title:
            other.append({"title": title, "done": b["done"], "open": opencount,
                          "post_mvp": _milestone_num(title) == 6,
                          "closed": b["closed"]})
        if opencount > 0:
            chart_labels.append("m%02d" % _milestone_num(title))
            chart_vals.append(opencount)
    ymax = (max(chart_vals) + 1) if chart_vals else 1

    return {
        "repo": repo,
        "as_of": as_of,
        "cap": cap,
        "focus": {"milestone": focus_title, "done": fb["done"],
                  "ready": fb["ready"], "in_planning": fb["in_planning"],
                  "unplanned": fb["unplanned"], "queue": queue},
        "your_move": {"prs": len(awaiting), "release_please": len(automation),
                      "new_ideas": len(intake), "approvals": len(pending),
                      "questions": len(needs)},
        "prs": {"awaiting": awaiting, "automation": automation},
        "intake": intake,
        "pending_approval": pending,
        "needs_clarification": needs,
        "parked": parked,
        "other_milestones": other,
        "open_by_milestone": {"labels": chart_labels, "values": chart_vals,
                              "ymax": ymax},
        "reconcile": _reconcile_block(repo, token, issues),
    }


_RECONCILE_MOD = None


def _reconcile_mod():
    """Load ``pipeline-reconcile``'s ``reconcile`` module once and cache it.

    The dashboard reuses reconcile's canonical helpers — ``merge_blockers`` (the
    one shared hard-blocker merge rule, #321) and ``native_blocked_by`` (the
    native issue-dependency fetcher) — so the blocker graph the dashboard reads
    is identical to the one reconcile / the nightly builder / the #212
    milestone-order gate read. No duplicated parsing.
    """
    global _RECONCILE_MOD
    if _RECONCILE_MOD is None:
        import importlib.util
        here = os.path.dirname(os.path.abspath(__file__))
        path = os.path.join(here, os.pardir, "pipeline-reconcile", "reconcile.py")
        spec = importlib.util.spec_from_file_location("pipeline_reconcile", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        _RECONCILE_MOD = mod
    return _RECONCILE_MOD


def _merged_blocked_by(body, native_refs=()):
    """One issue's hard blockers: structured ``Blocked by: #N`` text lines
    UNIONED with native GitHub issue-dependency blockers (``native_refs``),
    de-duped and sorted via the canonical ``merge_blockers`` helper (#321).

    Feeds both the "Blocked by" columns and the ``compute_unblockers`` graph, so
    both read native the same way — never prose. ``native_refs`` defaults to
    empty so the text line alone still works during migration. Soft
    ``Depends on:`` ordering has no native form and is not merged here.
    """
    return _reconcile_mod().merge_blockers(_blocked_by(body), native_refs)


def _reconcile_block(repo, token, issues):
    """Populate the dashboard's ``reconcile`` block from the sweep's findings.

    Delegates detection to the single source of truth — ``pipeline-reconcile``'s
    pure ``process`` over its own live snapshot — then resolves the flagged
    issue numbers to titles from the issues this renderer already fetched.
    I/O-layer only; not exercised by the render unit tests.
    """
    mod = _reconcile_mod()
    findings = mod.process(mod.fetch_state(repo, token))
    titles = {i["number"]: _clean(i["title"]) for i in issues}

    def rows(items):
        return [{"number": f["number"], "title": titles.get(f["number"], "")}
                for f in items]

    prose = [{"number": f["number"], "title": titles.get(f["number"], ""),
              "refs": f.get("refs", [])} for f in findings["flag_prose_dep"]]
    stuck = [{"number": f["number"], "title": titles.get(f["number"], ""),
              "handback_state": f.get("handback_state", ""),
              "handbacks": f.get("handbacks", 0)}
             for f in findings.get("flag_stuck_triage", [])]
    return {
        "flag_done": rows(findings["flag_done"]),
        "orphaned_ready": rows(findings["flag_orphaned_ready"]),
        "prose_dep": prose,
        "stuck_triage": stuck,
        "auto_fixed": {"strip_labels": len(findings["strip_labels"]),
                       "requeue": len(findings["requeue"])},
    }


def _clean(title):
    # GitHub API returns raw titles; collapse whitespace, keep it one line.
    return " ".join((title or "").split())


def _milestone_title(issue):
    """Milestone title for one issue's per-issue state dict (#336).

    Returns the milestone's title when set, or ``""`` when the issue has no
    milestone — the empty string renders as a blank Milestone cell.
    """
    ms = issue.get("milestone")
    return ms["title"] if ms else ""


def _read_focus_marker(body):
    import re
    m = re.search(r"<!--\s*pipeline-focus:\s*(.+?)\s*-->", body)
    return m.group(1).strip() if m else None


def _read_cap_marker(body):
    """Read the hidden `<!-- pipeline-cap: N -->` marker (#240).

    Mirrors `_read_focus_marker`. Returns the parsed int, or None if the
    marker is absent or its value isn't a plain integer.
    """
    import re
    m = re.search(r"<!--\s*pipeline-cap:\s*(-?\d+)\s*-->", body)
    return int(m.group(1)) if m else None


def _resolve_cap(override, marker_value):
    """Cap precedence: an explicit override (the `DASHBOARD_SET_CAP` env var,
    set when a `/cap` command re-renders the dashboard) wins; else the #193
    marker; else `DEFAULT_CAP` (3, matching `select_queue.py`'s own
    fallback). Mirrors the historical `_resolve_focus` precedence
    (override → marker → default) used for `DASHBOARD_SET_FOCUS`.

    An override that isn't a positive integer (blank, non-numeric,
    zero/negative) is treated as absent and falls through to the marker —
    the same "reject silently invalid input rather than store it" rule
    `/cap` enforces at the parser layer.
    """
    if override is not None:
        text = str(override).strip()
        if text:
            try:
                n = int(text)
            except ValueError:
                n = None
            if n is not None and n > 0:
                return n
    if marker_value is not None:
        return marker_value
    return DEFAULT_CAP


def _resolve_focus(override, marker_value, fallback):
    """Focus precedence: an explicit override (the `DASHBOARD_SET_FOCUS` env
    var, set when a `/focus` command re-renders the dashboard) wins; else the
    #193 marker; else `fallback` (the lowest version milestone with open
    ready-for-work issues). Mirrors `_resolve_cap`'s override → marker →
    default precedence, and restores the `DASHBOARD_SET_FOCUS` override dropped
    in #238 (the parked #204/#234 gap).

    A blank/whitespace-only override is treated as absent and falls through to
    the marker. Unlike `/cap`'s numeric check, an override's *validity*
    (naming a live milestone) is enforced upstream at the parser layer
    (`parse_commands` rejects an unmatched `/focus` as `focus-no-match`), so a
    non-blank override reaching here is trusted verbatim.
    """
    if override is not None:
        text = str(override).strip()
        if text:
            return text
    if marker_value:
        return marker_value
    return fallback


def _blocked_by(body):
    import re
    nums = []
    for m in re.finditer(r"[Bb]locked by:?\s*#(\d+)", body):
        nums.append(int(m.group(1)))
    return nums


def _patch_issue_body(repo, number, body, token):
    data = json.dumps({"body": body}).encode()
    req = urllib.request.Request(
        "%s/repos/%s/issues/%d" % (API, repo, number), data=data, method="PATCH")
    req.add_header("Authorization", "Bearer %s" % token)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "doggiehood-dashboard")
    req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req) as resp:
        return resp.status


def main(argv):
    if "--render-only" in argv:
        state = json.load(sys.stdin)
        sys.stdout.write(render_body(state))
        return 0

    repo = os.environ.get("DASHBOARD_REPO", REPO_DEFAULT)
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.stderr.write("GITHUB_TOKEN is required for live fetch.\n")
        return 2
    as_of = os.environ.get("DASHBOARD_AS_OF", "")
    state = fetch_state(repo, token, as_of)
    body = render_body(state)
    if "--write" in argv:
        status = _patch_issue_body(repo, DASHBOARD_ISSUE, body, token)
        sys.stderr.write("PATCH #%d -> %s\n" % (DASHBOARD_ISSUE, status))
    else:
        sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
