#!/usr/bin/env python3
"""Deterministic renderer for the Doggiehood daily pipeline dashboard (#193).

Two responsibilities, cleanly split so the render is testable without network:

  * ``render_body(state)`` — PURE. Turns a state dict into the exact markdown
    body of issue #193. Golden-tested; no GitHub I/O.
  * ``fetch_state(repo, token)`` — queries the GitHub REST API (stdlib urllib,
    no third-party deps) and assembles the state dict.

Entry points:
  * ``render_dashboard.py --render-only``  reads a state JSON on stdin and
    prints the body (used by tests and for local preview).
  * ``render_dashboard.py``                fetches live state and prints the
    body.
  * ``render_dashboard.py --write``        fetches, renders, and PATCHes #193.

Auth: uses ``GITHUB_TOKEN`` from the environment (the token GitHub Actions
injects), so the whole thing runs headless in the scheduled workflow with no
LLM in the loop. See docs/engineering/issue-pipeline.md.
"""

import json
import os
import sys
import urllib.error
import urllib.request

REPO_DEFAULT = "derekwinters/lucas-doggiehood"
DASHBOARD_ISSUE = 193
API = "https://api.github.com"

# Focus-milestone pie colors (done / ready-for-work / remaining).
PIE_DONE = "#3fae5a"
PIE_READY = "#e6c200"
PIE_REMAIN = "#d64545"

BAR_CELLS = 10  # width of the ▰▱ progress bars in "Other milestones"


def _issue_link(repo, number):
    return "[#%d](https://github.com/%s/issues/%d)" % (number, repo, number)


def _pr_link(repo, number):
    return "[#%d](https://github.com/%s/pull/%d)" % (number, repo, number)


def _progress_bar(done, total):
    if total <= 0:
        filled = 0
    else:
        filled = round(done / total * BAR_CELLS)
    filled = max(0, min(BAR_CELLS, filled))
    return "▰" * filled + "▱" * (BAR_CELLS - filled)


def render_body(state):
    repo = state.get("repo", REPO_DEFAULT)
    focus = state["focus"]
    fm = focus["milestone"]
    done, ready, remaining = focus["done"], focus["ready"], focus["remaining"]
    total = done + ready + remaining
    ym = state["your_move"]

    L = []
    a = L.append

    # Hidden focus marker — the single source of truth read by the gatekeeper
    # and pipeline-dev. MUST be the first line.
    a("<!-- pipeline-focus: %s -->" % fm)
    a("")
    a("_Auto-generated by the dashboard workflow — do not edit by hand; "
      "it is rewritten on a schedule and never closed._")
    a("")
    a("**As of:** %s · **Focus milestone:** `%s`" % (state["as_of"], fm))
    a("")

    # --- Focus milestone -------------------------------------------------
    a("## 🎯 Focus milestone — `%s`" % fm)
    a("**%d / %d complete**" % (done, total))
    a("")
    a("```mermaid")
    a('%%{init: {"themeVariables": {"pie1": "' + PIE_DONE
      + '", "pie2": "' + PIE_READY + '", "pie3": "' + PIE_REMAIN + '"}}}%%')
    a("pie showData title %s" % fm)
    a('    "Done" : %d' % done)
    a('    "Ready for work" : %d' % ready)
    a('    "Remaining" : %d' % remaining)
    a("```")
    a("")
    a("**▶️ Ready-for-work queue** _(this milestone only, in nightly build order)_")
    a("")
    queue = focus.get("queue", [])
    if queue:
        a("| Issue | Title | |")
        a("| - | - | - |")
        for it in queue:
            flag = " ⛔ _blocked_" if it.get("blocked") else ""
            a("| %s | %s |%s |" % (_issue_link(repo, it["number"]), it["title"], flag))
    else:
        a("_Nothing queued yet. `/approve` an analysis into this milestone and "
          "it lands here, blockers first. Set the active milestone anytime with "
          "`/focus <milestone>`._")
    a("")
    a("---")
    a("")

    # --- Your move -------------------------------------------------------
    a("### 🔔 Your move")
    a("| Queue | Count |")
    a("| - | - |")
    a("| 🔀 PRs awaiting your merge | **%d** (+%d release-please, below) |"
      % (ym["prs"], ym["release_please"]))
    a("| 🆕 New ideas to `/admit` | **%d** |" % ym["new_ideas"])
    a("| ✅ Analyses to `/approve` | **%d** |" % ym["approvals"])
    a("| ❓ Questions to answer | **%d** |" % ym["questions"])
    a("")
    a("---")
    a("")

    # --- Pull requests ---------------------------------------------------
    a("## 🔀 Pull requests")
    a("")
    awaiting = state["prs"].get("awaiting", [])
    if awaiting:
        a("**Awaiting your merge:**")
        a("")
        a("| PR | Title | State |")
        a("| - | - | - |")
        for pr in awaiting:
            a("| %s | `%s` | %s |"
              % (_pr_link(repo, pr["number"]), pr["title"], pr.get("state", "")))
    else:
        a("**Awaiting your merge:** _none right now._")
    a("")
    automation = state["prs"].get("automation", [])
    if automation:
        a("**Automation (separate cadence):**")
        a("")
        a("| PR | Title | State |")
        a("| - | - | - |")
        for pr in automation:
            a("| %s | `%s` | %s |"
              % (_pr_link(repo, pr["number"]), pr["title"], pr.get("state", "")))
        a("")
    a("---")
    a("")

    # --- New ideas (intake) ----------------------------------------------
    a("## 🆕 New ideas — awaiting your call")
    a("_Raw, ungated issues. `/admit` pulls one into analysis · `/park` hides it._")
    a("")
    _issue_table(a, repo, state.get("intake", []))
    a("")
    a("> **Your move:** `/admit` · `/park`")
    a("")
    a("---")
    a("")

    # --- Pending approval ------------------------------------------------
    a("## ✅ Pending approval — analysis done, awaiting you")
    a("_AI has triaged these; read the analysis on each, then act._")
    a("")
    _issue_table(a, repo, state.get("pending_approval", []))
    a("")
    a("> **Your move:** `/approve` (→ ready-for-work, milestone as proposed) · "
      "`/revise <notes>` · `/redo` · `/park`")
    a("")
    a("---")
    a("")

    # --- Needs clarification ---------------------------------------------
    a("## ❓ Needs clarification — blocked on your answer")
    a("_A specific question is posted on each issue — open it to read and reply._")
    a("")
    _issue_table(a, repo, state.get("needs_clarification", []))
    a("")
    a("> **Your move:** `/revise <notes>` · `/redo` · `/propose` · `/park`")
    a("")
    a("---")
    a("")

    # --- Other milestones ------------------------------------------------
    a("## 📦 Other milestones")
    a("_Live counts for every milestone outside the current focus._")
    a("")
    a("| Milestone | Progress | |")
    a("| - | - | - |")
    for m in state.get("other_milestones", []):
        mdone, mopen = m["done"], m["open"]
        mtotal = mdone + mopen
        bar = _progress_bar(mdone, mtotal)
        note = " · _post-MVP_" if m.get("post_mvp") else ""
        a("| `%s` | `%s` | %d/%d complete · %d open%s |"
          % (m["title"], bar, mdone, mtotal, mopen, note))
    a("")
    a("---")
    a("")

    # --- Open issues by milestone chart ----------------------------------
    obm = state.get("open_by_milestone")
    if obm and obm.get("values"):
        a("## 📈 Open issues by milestone")
        a("")
        a("```mermaid")
        a("xychart-beta")
        a('    title "Open issues by milestone"')
        a("    x-axis [%s]" % ", ".join(obm["labels"]))
        a('    y-axis "Open issues" 0 --> %d' % obm["ymax"])
        a("    bar [%s]" % ", ".join(str(v) for v in obm["values"]))
        a("```")
        a("")
        a("---")
        a("")

    # --- Command reference (static) --------------------------------------
    a("### 📖 Command reference")
    a("Comment on any issue (only Derek's commands are honored):")
    a("")
    a("| Command | Effect |")
    a("| - | - |")
    a("| `/admit` | Pull a raw idea into AI analysis |")
    a("| `/approve` | Accept the analysis → ready-for-work, sets proposed milestone |")
    a("| `/revise <notes>` | Send back to analysis with your feedback |")
    a("| `/redo` | Discard the analysis and start it over |")
    a("| `/propose` | Authorize AI to draft the missing design/wireframe as a proposal |")
    a("| `/park` / `/unpark` | Hide from the pipeline / bring it back |")
    a("| `/milestone <name>` | Override the milestone |")
    a("| `/focus <name>` | Set the active milestone for nightly development |")

    return "\n".join(L) + "\n"


def _issue_table(a, repo, issues):
    if not issues:
        a("_None right now._")
        return
    a("| Issue | Summary |")
    a("| - | - |")
    for it in issues:
        a("| %s | %s |" % (_issue_link(repo, it["number"]), it["title"]))


# --------------------------------------------------------------------------
# Live-state fetch (GitHub REST API via stdlib urllib). Not exercised by the
# unit tests, which drive render_body() directly with a fixture.
# --------------------------------------------------------------------------

def _api_get(path, token):
    req = urllib.request.Request(API + path)
    req.add_header("Authorization", "Bearer %s" % token)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "doggiehood-dashboard")
    with urllib.request.urlopen(req) as resp:
        return json.load(resp)


def _paginate(path, token):
    items, page = [], 1
    sep = "&" if "?" in path else "?"
    while True:
        batch = _api_get("%s%sper_page=100&page=%d" % (path, sep, page), token)
        if not batch:
            break
        items.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return items


def _milestone_num(title):
    import re
    m = re.match(r"^0*(\d+)", title or "")
    return int(m.group(1)) if m else 9999


def fetch_state(repo, token, as_of):
    raw = _paginate("/repos/%s/issues?state=all" % repo, token)
    issues = [i for i in raw if "pull_request" not in i]

    def labels_of(i):
        return {l["name"] for l in i.get("labels", [])}

    # Milestone roll-up.
    milestones = {}
    for i in issues:
        ms = i.get("milestone")
        if not ms:
            continue
        title = ms["title"]
        lbl = labels_of(i)
        if "dashboard" in lbl or "type:epic" in lbl or "parked" in lbl:
            continue
        b = milestones.setdefault(title, {"done": 0, "ready": 0, "remaining": 0})
        if i["state"] == "closed":
            b["done"] += 1
        elif "ready-for-work" in lbl:
            b["ready"] += 1
        else:
            b["remaining"] += 1

    # Focus: marker on #193 if present, else lowest milestone with ready work.
    dash = _api_get("/repos/%s/issues/%d" % (repo, DASHBOARD_ISSUE), token)
    focus_title = _read_focus_marker(dash.get("body") or "")
    if not focus_title:
        ready_ms = [t for t, b in milestones.items() if b["ready"] > 0]
        pool = ready_ms or list(milestones)
        focus_title = min(pool, key=_milestone_num) if pool else "(none)"
    fb = milestones.get(focus_title, {"done": 0, "ready": 0, "remaining": 0})

    def open_issues_with(label):
        out = []
        for i in issues:
            if i["state"] != "open":
                continue
            lbl = labels_of(i)
            if i["number"] == DASHBOARD_ISSUE or "parked" in lbl or "type:epic" in lbl:
                continue
            if label(lbl):
                out.append({"number": i["number"], "title": _clean(i["title"])})
        return out

    intake = open_issues_with(lambda l: not (l & {
        "ai-triage", "pending-approval", "needs-clarification",
        "ready-for-work", "in-progress"}))
    pending = open_issues_with(lambda l: "pending-approval" in l)
    needs = open_issues_with(lambda l: "needs-clarification" in l)

    # Focus ready-for-work queue.
    queue = []
    open_numbers = {i["number"] for i in issues if i["state"] == "open"}
    for i in issues:
        lbl = labels_of(i)
        ms = i.get("milestone")
        if (i["state"] == "open" and "ready-for-work" in lbl
                and ms and ms["title"] == focus_title and "parked" not in lbl):
            blocked = any(b in open_numbers for b in _blocked_by(i.get("body") or ""))
            queue.append({"number": i["number"], "title": _clean(i["title"]),
                          "blocked": blocked})
    queue.sort(key=lambda q: (q["blocked"], q["number"]))

    # Pull requests.
    pulls = _paginate("/repos/%s/pulls?state=open" % repo, token)
    awaiting, automation = [], []
    for p in pulls:
        title = p["title"]
        is_rp = (title.startswith("chore(main): release")
                 or p["head"]["ref"].startswith("release-please"))
        entry = {"number": p["number"], "title": title,
                 "state": "release-please — merge to cut the release" if is_rp
                 else "open"}
        (automation if is_rp else awaiting).append(entry)

    # Other-milestone summaries + open-by-milestone chart.
    other, chart_labels, chart_vals = [], [], []
    for title in sorted(milestones, key=_milestone_num):
        b = milestones[title]
        opencount = b["ready"] + b["remaining"]
        if title != focus_title:
            other.append({"title": title, "done": b["done"], "open": opencount,
                          "post_mvp": _milestone_num(title) == 6})
        if opencount > 0:
            chart_labels.append("m%02d" % _milestone_num(title))
            chart_vals.append(opencount)
    ymax = (max(chart_vals) + 1) if chart_vals else 1

    return {
        "repo": repo,
        "as_of": as_of,
        "focus": {"milestone": focus_title, "done": fb["done"],
                  "ready": fb["ready"], "remaining": fb["remaining"],
                  "queue": queue},
        "your_move": {"prs": len(awaiting), "release_please": len(automation),
                      "new_ideas": len(intake), "approvals": len(pending),
                      "questions": len(needs)},
        "prs": {"awaiting": awaiting, "automation": automation},
        "intake": intake,
        "pending_approval": pending,
        "needs_clarification": needs,
        "other_milestones": other,
        "open_by_milestone": {"labels": chart_labels, "values": chart_vals,
                              "ymax": ymax},
    }


def _clean(title):
    # GitHub API returns raw titles; collapse whitespace, keep it one line.
    return " ".join((title or "").split())


def _read_focus_marker(body):
    import re
    m = re.search(r"<!--\s*pipeline-focus:\s*(.+?)\s*-->", body)
    return m.group(1).strip() if m else None


def _blocked_by(body):
    import re
    nums = []
    for m in re.finditer(r"[Bb]locked by:?\s*#(\d+)", body):
        nums.append(int(m.group(1)))
    return nums


def _patch_issue_body(repo, number, body, token):
    data = json.dumps({"body": body}).encode()
    req = urllib.request.Request(
        "%s/repos/%s/issues/%d" % (API, repo, number), data=data, method="PATCH")
    req.add_header("Authorization", "Bearer %s" % token)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "doggiehood-dashboard")
    req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req) as resp:
        return resp.status


def main(argv):
    if "--render-only" in argv:
        state = json.load(sys.stdin)
        sys.stdout.write(render_body(state))
        return 0

    repo = os.environ.get("DASHBOARD_REPO", REPO_DEFAULT)
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.stderr.write("GITHUB_TOKEN is required for live fetch.\n")
        return 2
    as_of = os.environ.get("DASHBOARD_AS_OF", "")
    state = fetch_state(repo, token, as_of)
    body = render_body(state)
    if "--write" in argv:
        status = _patch_issue_body(repo, DASHBOARD_ISSUE, body, token)
        sys.stderr.write("PATCH #%d -> %s\n" % (DASHBOARD_ISSUE, status))
    else:
        sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
