using System;
using System.Linq;
using Doggiehood.Core.Dogs;
using Doggiehood.Core.Economy;
using Doggiehood.Core.Quests;
using Doggiehood.Core.World;
using NUnit.Framework;

namespace Doggiehood.Core.Tests.Quests
{
    /// <summary>
    /// #704: the quest board is durable. Active quests used to be session-only
    /// — "regenerated by the daily rotation" — which stopped being true once
    /// the refresh became an hourly trickle (#543/#624) that tops up by one:
    /// every relaunch wiped the board and refilled a single quest. Worse, an
    /// accepted paid quest (#626) charges the item cost on accept and saves,
    /// so the spend was durable while the quest that reimburses it was not.
    /// </summary>
    public class QuestPersistenceTests
    {
        private static GameState PlayableState()
        {
            var state = GameState.CreateNew();
            state.MarkOnboardingComplete();
            state.Wallet.Deposit(500);
            return state;
        }

        private static Quest Reloaded(GameState state, Quest quest, out GameState reloaded)
        {
            reloaded = SaveCodec.Load(SaveCodec.Save(state));
            return reloaded.Quests.ActiveQuests.FirstOrDefault(q => q.Id == quest.Id);
        }

        [Test]
        public void AvailableQuest_RoundTrips_WithItsWholeOffer()
        {
            var state = PlayableState();
            var quest = state.Quests.GiveQuestTo(state.Dogs[0], QuestType.LostItem, new Random(1));

            var restored = Reloaded(state, quest, out _);

            Assert.That(restored, Is.Not.Null, "an offered quest survives the relaunch");
            Assert.That(restored.Type, Is.EqualTo(QuestType.LostItem));
            Assert.That(restored.DogName, Is.EqualTo(quest.DogName));
            Assert.That(restored.ItemName, Is.EqualTo(quest.ItemName));
            Assert.That(restored.Status, Is.EqualTo(QuestStatus.Available));
            Assert.That(restored.DialogueLines, Is.EqualTo(quest.DialogueLines),
                "the chosen dialogue is not re-rolled on load");
        }

        [Test]
        public void AcceptedLostItemQuest_RoundTrips_KeepingItsHiddenItemPosition()
        {
            var state = PlayableState();
            var quest = state.Quests.GiveQuestTo(state.Dogs[0], QuestType.LostItem, new Random(2));
            Assert.That(state.Quests.Accept(quest), Is.True, "precondition: the quest accepts");

            var restored = Reloaded(state, quest, out var reloaded);

            Assert.That(restored.Status, Is.EqualTo(QuestStatus.Accepted));
            Assert.That(restored.HiddenItemPosition.HasValue, Is.True, "the item stays where it was hidden");
            Assert.That(restored.HiddenItemPosition.Value.X,
                Is.EqualTo(quest.HiddenItemPosition.Value.X).Within(0.0001f));
            Assert.That(restored.HiddenItemPosition.Value.Z,
                Is.EqualTo(quest.HiddenItemPosition.Value.Z).Within(0.0001f));
            Assert.That(reloaded.Quests.TapWorldPosition(restored.HiddenItemPosition.Value), Is.True,
                "and tapping that spot still completes the restored quest");
        }

        [Test]
        public void AcceptedPestControlQuest_RoundTrips_AndItsHouseStillAwaitsSpray()
        {
            var state = PlayableState();
            var quest = state.Quests.GiveQuestTo(state.Dogs[0], QuestType.PestControl, new Random(3));
            state.Quests.Accept(quest);

            var restored = Reloaded(state, quest, out var reloaded);

            Assert.That(restored.TargetHouseId, Is.EqualTo(quest.TargetHouseId), "the afflicted house survives");
            Assert.That(reloaded.Quests.HousesAwaitingSpray(), Does.Contain(quest.TargetHouseId.Value),
                "the bugs are still on that house after a relaunch");
        }

        [Test]
        public void AcceptedBuyGift_MidDelivery_RoundTrips_WithoutRechargingTheWallet()
        {
            var state = PlayableState();
            var quest = state.Quests.GiveQuestTo(state.Dogs[0], QuestType.BuyGift, new Random(4));
            Assert.That(quest.ItemName, Is.Not.EqualTo(ItemCatalog.FenceItemName),
                "precondition: a gift with a real delivery leg (the fence completes on accept)");
            Assert.That(state.Quests.Accept(quest), Is.True, "precondition: the gift is bought");
            var coinsAfterPaying = state.Wallet.Coins;
            Assert.That(quest.DeliveryPhase, Is.EqualTo(DeliveryPhase.HeadingHome));

            var restored = Reloaded(state, quest, out var reloaded);

            Assert.That(restored, Is.Not.Null, "the job the player already paid for is still there");
            Assert.That(restored.Status, Is.EqualTo(QuestStatus.Accepted));
            Assert.That(restored.Cost, Is.EqualTo(quest.Cost), "the fronted cost survives, so completion reimburses it");
            Assert.That(reloaded.Wallet.Coins, Is.EqualTo(coinsAfterPaying),
                "the relaunch neither re-charges the player nor refunds them");
        }

        [Test]
        public void AcceptedBuyGift_RestoresInAPhaseSomethingStillDrives()
        {
            // The truck is an in-flight view object and never survives a
            // relaunch, so a quest must never come back parked in a phase whose
            // only continuation was that truck — the player would have paid for
            // an item that could never arrive.
            var state = PlayableState();
            var quest = state.Quests.GiveQuestTo(state.Dogs[0], QuestType.BuyGift, new Random(5));
            state.Quests.Accept(quest);
            state.Quests.NotifyDogArrivedHome(quest);
            Assert.That(quest.DeliveryPhase, Is.EqualTo(DeliveryPhase.WaitingForDelivery),
                "precondition: the dog is sitting at the door waiting for the truck");

            var restored = Reloaded(state, quest, out _);

            Assert.That(restored.Status, Is.EqualTo(QuestStatus.Accepted), "the paid job is untouched");
            Assert.That(restored.DeliveryPhase, Is.EqualTo(DeliveryPhase.HeadingHome),
                "the delivery resumes from the walk home, which the director still drives");
        }

        [Test]
        public void DecorationRequest_RoundTrips_WithItsSelectableOptions()
        {
            var state = PlayableState();
            var quest = state.Quests.GiveQuestTo(state.Dogs[0], QuestType.DecorationRequest, new Random(6));
            Assert.That(quest.Options.Count, Is.GreaterThan(1), "precondition: the request offers a choice");

            var restored = Reloaded(state, quest, out var reloaded);

            Assert.That(restored.Options, Is.EqualTo(quest.Options), "the same options are still on offer");
            Assert.That(reloaded.Quests.AcceptWithChoice(restored, restored.Options[0]), Is.True,
                "and choosing one still works after the relaunch");
        }

        [Test]
        public void RestoredQuest_KeepsItsDogBooked_SoNoDogHoldsTwoQuests()
        {
            var state = PlayableState();
            var quest = state.Quests.GiveQuestTo(state.Dogs[0], QuestType.LostItem, new Random(7));

            var reloaded = SaveCodec.Load(SaveCodec.Save(state));

            var dog = reloaded.Dogs.First(d => d.Name == quest.DogName);
            Assert.That(dog.HasActiveQuest, Is.True, "the dog still has its quest to hand out");
            Assert.That(reloaded.Dogs.Count(d => d.HasActiveQuest), Is.EqualTo(1),
                "and nobody else was booked by the restore");
        }

        [Test]
        public void CompletedQuest_IsNotPersisted_AndIsNeverRepaid()
        {
            var state = PlayableState();
            var quest = state.Quests.GiveQuestTo(state.Dogs[0], QuestType.PestControl, new Random(8));
            state.Quests.Accept(quest);
            Assert.That(state.Quests.SprayHouse(quest.TargetHouseId.Value), Is.True, "precondition: completed");
            var coinsAfterPayout = state.Wallet.Coins;

            var saved = SaveCodec.Save(state);
            var reloaded = SaveCodec.Load(saved);

            Assert.That(saved, Does.Not.Contain("quest="), "a finished quest leaves nothing in the save");
            Assert.That(reloaded.Quests.ActiveQuests, Is.Empty);
            Assert.That(reloaded.Wallet.Coins, Is.EqualTo(coinsAfterPayout), "and its payout is never paid twice");
        }

        [Test]
        public void RestoredQuestIds_DoNotCollideWithQuestsAddedAfterTheRelaunch()
        {
            var state = PlayableState();
            state.Quests.GiveQuestTo(state.Dogs[0], QuestType.LostItem, new Random(9));
            var second = state.Quests.GiveQuestTo(state.Dogs[1], QuestType.PestControl, new Random(10));

            var reloaded = SaveCodec.Load(SaveCodec.Save(state));
            var fresh = reloaded.Quests.GiveQuestTo(reloaded.Dogs[2], QuestType.LostItem, new Random(11));

            Assert.That(fresh.Id, Is.GreaterThan(second.Id), "the id counter resumes past every restored quest");
            Assert.That(reloaded.Quests.ActiveQuests.Select(q => q.Id).Distinct().Count(),
                Is.EqualTo(reloaded.Quests.ActiveQuests.Count()), "so no two active quests share an id");
        }

        [Test]
        public void ARelaunchRemovesNoActiveQuest()
        {
            // The durability invariant, stated as a test: closing the app is
            // never a reset. Every offered quest is still on the board.
            var state = PlayableState();
            state.Quests.GiveQuestTo(state.Dogs[0], QuestType.LostItem, new Random(12));
            state.Quests.GiveQuestTo(state.Dogs[1], QuestType.PestControl, new Random(13));
            state.Quests.GiveQuestTo(state.Dogs[2], QuestType.BuyGift, new Random(14));
            var before = state.Quests.ActiveQuests.Select(q => q.Id).OrderBy(id => id).ToList();

            var reloaded = SaveCodec.Load(SaveCodec.Save(state));

            Assert.That(reloaded.Quests.ActiveQuests.Select(q => q.Id).OrderBy(id => id).ToList(),
                Is.EqualTo(before), "the board that was there at close is the board that comes back");
        }

        [Test]
        public void DialogueAndItemText_SurviveSeparatorCharacters()
        {
            // Guard for the save's line/field separators: authored copy is free
            // text, so a comma or a pipe in a dialogue line must not corrupt the
            // rest of the save.
            var state = PlayableState();
            var quest = state.Quests.RestoreQuest(
                42, QuestType.LostItem, state.Dogs[0].Name, "toy",
                new[] { "Oh no, I lost it | somewhere!", "Help, please?" },
                new GridPoint(1.25f, -3.5f), null, null, Array.Empty<string>(),
                QuestStatus.Available, DeliveryPhase.None);
            Assert.That(quest, Is.Not.Null, "precondition: the quest was restored");

            var reloaded = SaveCodec.Load(SaveCodec.Save(state));

            var restored = reloaded.Quests.ActiveQuests.First(q => q.Id == 42);
            Assert.That(restored.DialogueLines, Is.EqualTo(quest.DialogueLines));
            Assert.That(reloaded.Wallet.Coins, Is.EqualTo(state.Wallet.Coins),
                "and the lines after it parse normally");
        }
    }
}
