using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Doggiehood.Core.Art;
using Doggiehood.Core.Onboarding;

namespace Doggiehood.Core.World
{
    /// <summary>
    /// Serializes the durable parts of GameState (#27). A simple line format
    /// keeps Core free of JSON/engine dependencies; the Unity layer decides
    /// where the string lives on disk (local save only — no accounts, no
    /// backend).
    ///
    /// <para>#704: "durable" now means the whole neighborhood — coins, the map,
    /// houses, every dog that moved in, and every uncompleted quest. It used to
    /// say active quests were regenerated by the rotation rather than persisted,
    /// "because quests never expire (#28)"; that stopped being true once a
    /// refresh became an hourly trickle of one, so a wiped board came back with
    /// a single quest. Only presentation stays session-only (positions,
    /// animations, in-flight view objects such as the delivery truck and the
    /// delivered package, #703). See docs/specs/product-scope.md "Saved
    /// state".</para>
    ///
    /// <para>The format is additive: the loader acts only on keys it knows and
    /// every field has a defined absent-value behavior, so a new record type
    /// needs no schema version bump and an older save keeps loading. Anything
    /// that cannot be defaulted gets an explicit migration at the end of
    /// <see cref="Load"/> instead.</para>
    /// </summary>
    public static class SaveCodec
    {
        private const string Version = "1";

        /// <summary>#704: fields on a <c>dog=</c> line
        /// (houseId|breed|personality|isPuppy|coat|name). Also the split cap, so
        /// the trailing name field absorbs the rest of the line.</summary>
        private const int DogFieldCount = 6;

        /// <summary>#704: fields on a <c>quest=</c> line — id, type, status,
        /// delivery phase, dog name, item name, cost, target house, hidden X,
        /// hidden Z, dialogue lines, options.</summary>
        private const int QuestFieldCount = 12;

        /// <summary>An optional integer field: its value, or an empty field for
        /// null (how the codec spells "this quest has no cost / no target
        /// house / nothing hidden").</summary>
        private static string Optional(int? value)
        {
            return value.HasValue ? value.Value.ToString(CultureInfo.InvariantCulture) : string.Empty;
        }

        private static int? ParseOptionalInt(string field)
        {
            return string.IsNullOrEmpty(field)
                ? (int?)null
                : int.Parse(field, CultureInfo.InvariantCulture);
        }

        public static string Save(GameState state)
        {
            var builder = new StringBuilder();
            builder.Append("version=").Append(Version).Append('\n');
            builder.Append("coins=").Append(state.Wallet.Coins.ToString(CultureInfo.InvariantCulture)).Append('\n');
            builder.Append("onboarded=").Append(state.OnboardingComplete ? "1" : "0").Append('\n');

            // #295: player-choice frontier tiles, unlocked one at a time. The
            // set of unlocked coordinates (with each tile's type so the map can
            // be rebuilt without the authored target map on hand) round-trips
            // here, superseding the sequential zones= count for tiles unlocked
            // through GameState.TryUnlockTile. Emitted in unlock order so each
            // replayed placement finds its neighbor already down (#109
            // adjacency). Omitted entirely for a game that has unlocked none.
            foreach (var coordinate in state.UnlockedTiles)
            {
                builder.Append("tile=")
                    .Append(coordinate.Col.ToString(CultureInfo.InvariantCulture)).Append('|')
                    .Append(coordinate.Row.ToString(CultureInfo.InvariantCulture)).Append('|')
                    .Append(state.Map.GetTileAt(coordinate).ToString())
                    .Append('\n');
            }

            // #434: a zone lot's pre-assigned art variant (ladder + tint),
            // rolled and locked in when its zone unlocked. Only lots that are
            // assigned but NOT yet built need this line — a BUILT lot carries
            // its variant on the house= line below, so emitting it here too
            // would duplicate it. Emitted AFTER zones= (so the lots exist when
            // the load replays them) and BEFORE house=. A legacy save with no
            // such line still resolves the same variant via the deterministic
            // fallback in GameState.TryBuildHouse.
            foreach (var pair in state.AssignedLotVariants)
            {
                if (!state.IsLotBuildable(pair.Key))
                {
                    continue;
                }

                builder.Append("lotvariant=")
                    .Append(pair.Key.ToString(CultureInfo.InvariantCulture)).Append('|')
                    .Append(pair.Value.LadderId.ToString(CultureInfo.InvariantCulture)).Append('|')
                    .Append(pair.Value.TintIndex.ToString(CultureInfo.InvariantCulture))
                    .Append('\n');
            }

            // #299: zone-built houses (id >= 5). The 4 starters are recreated
            // by GameState.CreateNew every load, so only zone houses need
            // persisting — each as id|level|isVacant|ladderId|tintIndex so its
            // rolled art variant (ladder + tint) and progress survive relaunch.
            // Emitted AFTER zones= so the lots exist when the load replays them.
            foreach (var house in state.Houses)
            {
                if (!HouseVariantAssignment.IsZoneHouse(house.Id) || !house.Variant.HasValue)
                {
                    continue;
                }

                var variant = house.Variant.Value;
                builder.Append("house=")
                    .Append(house.Id.ToString(CultureInfo.InvariantCulture)).Append('|')
                    .Append(house.Level.ToString(CultureInfo.InvariantCulture)).Append('|')
                    .Append(house.IsVacant ? "1" : "0").Append('|')
                    .Append(variant.LadderId.ToString(CultureInfo.InvariantCulture)).Append('|')
                    .Append(variant.TintIndex.ToString(CultureInfo.InvariantCulture))
                    .Append('\n');
            }

            // #704: every dog that moved in during play, as
            // houseId|breed|personality|isPuppy|coat|name. The 8 roster dogs are
            // recreated by GameState.CreateNew on every load (like the 4
            // starting houses), so only the moved-in dogs need a line. Without
            // this the roster reset to the starting 8 every relaunch while the
            // house each household filled stayed persisted as occupied —
            // leaving a house with no residents that could never take another
            // move-in. Enums are stored by name (like rewardChain) so they
            // survive a reordering, and the name is escaped like any other free
            // text. Emitted AFTER house= so every resident's house exists by the
            // time the line is replayed.
            foreach (var dog in state.MovedInDogs)
            {
                builder.Append("dog=")
                    .Append(dog.HouseId.ToString(CultureInfo.InvariantCulture)).Append('|')
                    .Append(dog.Breed.ToString()).Append('|')
                    .Append(dog.Personality.ToString()).Append('|')
                    .Append(dog.IsPuppy ? "1" : "0").Append('|')
                    .Append(dog.Coat.ToString()).Append('|')
                    .Append(SaveFieldCodec.Escape(dog.Name))
                    .Append('\n');
            }

            // #704: every quest currently on the board, as
            // id|type|status|phase|dogName|itemName|cost|targetHouseId|hiddenX|
            // hiddenZ|dialogue|options. The header's old reasoning — "quests are
            // regenerated by the rotation, so nothing is lost" — stopped holding
            // when the refresh became an hourly trickle that tops up by one
            // (#543/#624): a wiped board came back with a single quest. And an
            // accepted paid quest (#626) has already spent the player's coins,
            // so dropping it loses money that was really deducted. Only
            // uncompleted quests are emitted — a completed one has already paid
            // out and placed its item, and its delivered package is deliberately
            // scene-only (#703). Free text is escaped (SaveFieldCodec) so
            // authored dialogue can hold the separators. Emitted AFTER dog= so
            // every quest's dog is on the roster when the line is replayed.
            foreach (var quest in state.Quests.ActiveQuests)
            {
                builder.Append("quest=")
                    .Append(quest.Id.ToString(CultureInfo.InvariantCulture)).Append('|')
                    .Append(quest.Type.ToString()).Append('|')
                    .Append(quest.Status.ToString()).Append('|')
                    .Append(quest.DeliveryPhase.ToString()).Append('|')
                    .Append(SaveFieldCodec.Escape(quest.DogName)).Append('|')
                    .Append(SaveFieldCodec.Escape(quest.ItemName)).Append('|')
                    .Append(Optional(quest.Cost)).Append('|')
                    .Append(Optional(quest.TargetHouseId)).Append('|')
                    .Append(quest.HiddenItemPosition.HasValue
                        ? quest.HiddenItemPosition.Value.X.ToString("R", CultureInfo.InvariantCulture)
                        : string.Empty)
                    .Append('|')
                    .Append(quest.HiddenItemPosition.HasValue
                        ? quest.HiddenItemPosition.Value.Z.ToString("R", CultureInfo.InvariantCulture)
                        : string.Empty)
                    .Append('|')
                    .Append(SaveFieldCodec.JoinList(quest.DialogueLines)).Append('|')
                    .Append(SaveFieldCodec.JoinList(quest.Options))
                    .Append('\n');
            }

            // #316: the onboarding reward-chain step, so the one-time chain
            // resumes where it left off and is never restarted or re-paid on
            // reload. Stored by name so it survives any future enum reordering.
            builder.Append("rewardChain=").Append(state.RewardChain.CurrentStep.ToString()).Append('\n');

            // #469: the house id the onboarding "upgrade a house" step is scoped
            // to (the first-quest dog's house). Emitted only once recorded, so a
            // pre-#469 or pre-handoff save omits it and loads with no restriction
            // (IsHouseUpgradeEligible defaults to allowing every house). Kept
            // alongside rewardChain= so the gate resumes correctly mid-chain.
            if (state.OnboardingUpgradeTargetHouseId.HasValue)
            {
                builder.Append("upgradeTarget=")
                    .Append(state.OnboardingUpgradeTargetHouseId.Value.ToString(CultureInfo.InvariantCulture))
                    .Append('\n');
            }

            // #437: the shared move-in state — the pity counter
            // (quests-since-last-move-in) and the not-yet-consumed easter-egg
            // and reserved-breed reserves — as
            // <questsSinceLastMoveIn>|<remaining egg names>|<remaining reserved
            // breeds>. Without this the accumulated move-in odds reset to the
            // 5% base and a used easter-egg name could reappear every session.
            // Breeds are stored by name (like rewardChain) so they survive an
            // enum reordering; either reserve segment is empty once exhausted.
            builder.Append("moveIn=")
                .Append(state.MoveInQuestsSinceLastMoveIn.ToString(CultureInfo.InvariantCulture))
                .Append('|')
                .Append(string.Join(",", state.MoveInRemainingEasterEggNames))
                .Append('|')
                .Append(string.Join(",", state.MoveInRemainingReservedBreeds))
                .Append('\n');

            // #310: the quest-rotation cadence marker. UTC round-trip format
            // ("O") preserves the exact instant and its UTC kind; the line is
            // omitted entirely until the first rotation has run (null marker).
            if (state.LastRotationUtc.HasValue)
            {
                builder.Append("rotatedUtc=")
                    .Append(state.LastRotationUtc.Value.ToUniversalTime()
                        .ToString("O", CultureInfo.InvariantCulture))
                    .Append('\n');
            }

            // #704: the UTC instant the quest board dropped below its target —
            // the start of the wait for the next trickle top-up. Persisted so
            // the wait is measured in elapsed time and never restarted by a
            // relaunch (a relaunch is never a reset and never a shortcut).
            // Omitted entirely while the board is full, since nothing is being
            // waited for; a legacy save with no line seeds it from rotatedUtc=
            // on load, so a returning player's time away still counts.
            if (state.QuestRefreshTimerStartedUtc.HasValue)
            {
                builder.Append("questTimerUtc=")
                    .Append(state.QuestRefreshTimerStartedUtc.Value.ToUniversalTime()
                        .ToString("O", CultureInfo.InvariantCulture))
                    .Append('\n');
            }

            // #543: the persisted fractional quest-pacing accumulator (the
            // leftover fraction of a quest carried between hourly trickle
            // refreshes). Round-tripped like the move-in pity counter so cadence
            // survives a relaunch; a legacy save with no line loads at the 0.0
            // default (round-trip "R" preserves the exact double).
            builder.Append("questPacingAcc=")
                .Append(state.QuestPacingAccumulator.ToString("R", CultureInfo.InvariantCulture))
                .Append('\n');

            foreach (var item in state.PlacedItems)
            {
                builder.Append("placed=")
                    .Append(item.HouseId.ToString(CultureInfo.InvariantCulture))
                    .Append('|')
                    .Append(item.ItemName)
                    .Append('\n');
            }

            foreach (var decoration in state.Decorations)
            {
                builder.Append("deco=")
                    .Append(decoration.HouseId.ToString(CultureInfo.InvariantCulture))
                    .Append('|')
                    .Append(decoration.ItemName)
                    .Append('|')
                    .Append(decoration.YardPosition.X.ToString(CultureInfo.InvariantCulture))
                    .Append('|')
                    .Append(decoration.YardPosition.Z.ToString(CultureInfo.InvariantCulture))
                    .Append('\n');
            }

            return builder.ToString();
        }

        public static GameState Load(string saved)
        {
            if (string.IsNullOrEmpty(saved))
            {
                throw new ArgumentException("Nothing to load.", nameof(saved));
            }

            var state = GameState.CreateNew();
            var sawRewardChain = false;
            var sawQuestTimer = false;

            foreach (var line in saved.Split('\n'))
            {
                var separator = line.IndexOf('=');
                if (separator < 0)
                {
                    continue;
                }

                var key = line.Substring(0, separator);
                var value = line.Substring(separator + 1);

                if (key == "onboarded")
                {
                    if (value == "1")
                    {
                        state.MarkOnboardingComplete();
                    }
                }
                else if (key == "rewardChain")
                {
                    sawRewardChain = true;
                    if (Enum.TryParse(value, out OnboardingRewardStep step))
                    {
                        state.RestoreRewardChainStep(step);
                    }
                }
                else if (key == "upgradeTarget")
                {
                    // #469: the onboarding upgrade-target house id — restore it
                    // so the "upgrade a house" step stays scoped to the
                    // first-quest dog's house across a reload. Absent for a
                    // legacy/pre-handoff save, which then imposes no restriction.
                    state.RestoreOnboardingUpgradeTargetHouseId(int.Parse(value, CultureInfo.InvariantCulture));
                }
                else if (key == "moveIn")
                {
                    // #437: questsSinceLastMoveIn|remaining egg names|remaining
                    // reserved breeds — restore the pity counter and both
                    // reserves without rolling dice. Absence of the line leaves
                    // CreateNew's default fresh MoveInSystem in place, so a
                    // legacy save needs no special path (like zones=/house=).
                    var parts = value.Split('|');
                    var quests = int.Parse(parts[0], CultureInfo.InvariantCulture);
                    var eggNames = parts[1].Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                    var breeds = new List<Dogs.Breed>();
                    foreach (var name in parts[2].Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries))
                    {
                        if (Enum.TryParse(name, out Dogs.Breed breed))
                        {
                            breeds.Add(breed);
                        }
                    }

                    state.RestoreMoveInState(quests, eggNames, breeds);
                }
                else if (key == "rotatedUtc")
                {
                    state.RecordRotationUtc(DateTime.Parse(
                        value, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind));
                }
                else if (key == "questTimerUtc")
                {
                    // #704: restore the start of the wait for the next top-up.
                    sawQuestTimer = true;
                    state.RecordQuestRefreshTimerStart(DateTime.Parse(
                        value, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind));
                }
                else if (key == "questPacingAcc")
                {
                    // #543: restore the fractional trickle accumulator so the
                    // hourly cadence is not reset on relaunch. Absence (a
                    // pre-#543 save) leaves CreateNew's 0.0 default in place.
                    state.RestoreQuestPacingAccumulator(
                        double.Parse(value, CultureInfo.InvariantCulture));
                }
                else if (key == "tile")
                {
                    // #295: col|row|type — restore a player-unlocked frontier
                    // tile. Emitted after zones= and in unlock order, so its
                    // neighbors (the starting tile, any restored zone, or an
                    // earlier tile) are already placed.
                    var parts = value.Split('|');
                    if (Enum.TryParse(parts[2], out TileType tileType))
                    {
                        state.RestoreUnlockedTile(
                            new TileCoordinate(
                                int.Parse(parts[0], CultureInfo.InvariantCulture),
                                int.Parse(parts[1], CultureInfo.InvariantCulture)),
                            tileType);
                    }
                }
                else if (key == "lotvariant")
                {
                    // #434: houseId|ladderId|tintIndex — restore a zone lot's
                    // pre-assigned (but not yet built) art variant. Emitted
                    // before house= lines, so the assignment is in place if a
                    // later build reads it; a built lot never has this line.
                    var parts = value.Split('|');
                    state.RestoreAssignedLotVariant(
                        int.Parse(parts[0], CultureInfo.InvariantCulture),
                        new HouseVariant(
                            int.Parse(parts[1], CultureInfo.InvariantCulture),
                            int.Parse(parts[2], CultureInfo.InvariantCulture)));
                }
                else if (key == "house")
                {
                    // #299: id|level|isVacant|ladderId|tintIndex — restore the
                    // zone house with its persisted variant. Relies on zones=
                    // having been processed already (emitted earlier).
                    var parts = value.Split('|');
                    state.RestoreBuiltHouse(
                        int.Parse(parts[0], CultureInfo.InvariantCulture),
                        int.Parse(parts[1], CultureInfo.InvariantCulture),
                        parts[2] == "1",
                        new HouseVariant(
                            int.Parse(parts[3], CultureInfo.InvariantCulture),
                            int.Parse(parts[4], CultureInfo.InvariantCulture)));
                }
                else if (key == "dog")
                {
                    // #704: houseId|breed|personality|isPuppy|coat|name —
                    // restore a moved-in dog onto the live roster. Split with a
                    // field cap so the trailing name keeps any character it
                    // likes. An unparseable enum means a save from a build that
                    // knew a value this one doesn't, so the line is skipped
                    // rather than crashing the whole load.
                    var parts = value.Split(new[] { '|' }, DogFieldCount);
                    if (parts.Length == DogFieldCount
                        && Enum.TryParse(parts[1], out Dogs.Breed dogBreed)
                        && Enum.TryParse(parts[2], out Dogs.Personality personality)
                        && Enum.TryParse(parts[4], out Dogs.CoatColor coat))
                    {
                        state.RestoreDog(new Dogs.Dog(
                            SaveFieldCodec.Unescape(parts[5]),
                            dogBreed,
                            personality,
                            int.Parse(parts[0], CultureInfo.InvariantCulture),
                            parts[3] == "1",
                            coat));
                    }
                }
                else if (key == "quest")
                {
                    // #704: rebuild an active quest exactly as it stood — no
                    // re-roll, no re-charge (QuestManager.RestoreQuest). Emitted
                    // after dog=, so the quest's dog is already on the roster.
                    var parts = value.Split('|');
                    if (parts.Length >= QuestFieldCount
                        && Enum.TryParse(parts[1], out Quests.QuestType questType)
                        && Enum.TryParse(parts[2], out Quests.QuestStatus questStatus)
                        && Enum.TryParse(parts[3], out Quests.DeliveryPhase deliveryPhase))
                    {
                        GridPoint? hidden = null;
                        if (!string.IsNullOrEmpty(parts[8]) && !string.IsNullOrEmpty(parts[9]))
                        {
                            hidden = new GridPoint(
                                float.Parse(parts[8], CultureInfo.InvariantCulture),
                                float.Parse(parts[9], CultureInfo.InvariantCulture));
                        }

                        state.Quests.RestoreQuest(
                            int.Parse(parts[0], CultureInfo.InvariantCulture),
                            questType,
                            SaveFieldCodec.Unescape(parts[4]),
                            string.IsNullOrEmpty(parts[5]) ? null : SaveFieldCodec.Unescape(parts[5]),
                            SaveFieldCodec.SplitList(parts[10]),
                            hidden,
                            ParseOptionalInt(parts[6]),
                            ParseOptionalInt(parts[7]),
                            SaveFieldCodec.SplitList(parts[11]),
                            questStatus,
                            deliveryPhase);
                    }
                }
                else if (key == "coins")
                {
                    var coins = int.Parse(value, CultureInfo.InvariantCulture);
                    if (coins > 0)
                    {
                        state.Wallet.Deposit(coins);
                    }
                }
                else if (key == "placed")
                {
                    var pipe = value.IndexOf('|');
                    var houseId = int.Parse(value.Substring(0, pipe), CultureInfo.InvariantCulture);
                    state.AddPlacedItem(houseId, value.Substring(pipe + 1));
                }
                else if (key == "deco")
                {
                    var parts = value.Split('|');
                    state.AddDecoration(new Decorations.Decoration(
                        parts[1],
                        int.Parse(parts[0], CultureInfo.InvariantCulture),
                        new GridPoint(
                            float.Parse(parts[2], CultureInfo.InvariantCulture),
                            float.Parse(parts[3], CultureInfo.InvariantCulture))));
                }
            }

            // #316 legacy migration: a pre-#316 save that finished onboarding
            // but carries no rewardChain field is a player long past onboarding
            // — treat the guided chain as already complete so it is never
            // re-offered and their rotation is never re-suppressed.
            if (!sawRewardChain && state.OnboardingComplete)
            {
                state.RestoreRewardChainStep(OnboardingRewardStep.Done);
            }

            // #704 legacy migration: a pre-#704 save has no refresh-timer line,
            // and its board loads empty (quests weren't persisted). Seed the
            // wait from the last rotation stamp — the closest thing that save
            // has to "when the board was last served" — so the player's time
            // away still counts instead of the hour restarting at the upgrade.
            if (!sawQuestTimer && state.LastRotationUtc.HasValue)
            {
                state.RecordQuestRefreshTimerStart(state.LastRotationUtc);
            }

            // #704 legacy migration: a pre-#704 save persisted a filled house as
            // occupied but never persisted the household that filled it. Any
            // house left with no resident is re-vacated here — the conservative
            // of the two options (rather than fabricating a dog that was never
            // rolled), so the house re-enters the move-in pool instead of
            // staying permanently dead. A no-op for a save that carries its
            // dog= lines.
            state.VacateHousesWithNoResidents();

            return state;
        }
    }
}
