using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Doggiehood.Core.World
{
    /// <summary>
    /// Serializes the durable parts of GameState (#27): coin balance and
    /// permanently placed items. A simple line format keeps Core free of
    /// JSON/engine dependencies; the Unity layer decides where the string
    /// lives on disk (local save only — no accounts, no backend).
    /// Active quests are regenerated by the daily rotation rather than
    /// persisted — nothing is lost because quests never expire (#28).
    /// </summary>
    public static class SaveCodec
    {
        private const string Version = "1";

        public static string Save(GameState state)
        {
            var builder = new StringBuilder();
            builder.Append("version=").Append(Version).Append('\n');
            builder.Append("coins=").Append(state.Wallet.Coins.ToString(CultureInfo.InvariantCulture)).Append('\n');

            foreach (var item in state.PlacedItems)
            {
                builder.Append("placed=")
                    .Append(item.HouseId.ToString(CultureInfo.InvariantCulture))
                    .Append('|')
                    .Append(item.ItemName)
                    .Append('\n');
            }

            foreach (var decoration in state.Decorations)
            {
                builder.Append("deco=")
                    .Append(decoration.HouseId.ToString(CultureInfo.InvariantCulture))
                    .Append('|')
                    .Append(decoration.ItemName)
                    .Append('|')
                    .Append(decoration.YardPosition.X.ToString(CultureInfo.InvariantCulture))
                    .Append('|')
                    .Append(decoration.YardPosition.Z.ToString(CultureInfo.InvariantCulture))
                    .Append('\n');
            }

            return builder.ToString();
        }

        public static GameState Load(string saved)
        {
            if (string.IsNullOrEmpty(saved))
            {
                throw new ArgumentException("Nothing to load.", nameof(saved));
            }

            var state = GameState.CreateNew();

            foreach (var line in saved.Split('\n'))
            {
                var separator = line.IndexOf('=');
                if (separator < 0)
                {
                    continue;
                }

                var key = line.Substring(0, separator);
                var value = line.Substring(separator + 1);

                if (key == "coins")
                {
                    var coins = int.Parse(value, CultureInfo.InvariantCulture);
                    if (coins > 0)
                    {
                        state.Wallet.Deposit(coins);
                    }
                }
                else if (key == "placed")
                {
                    var pipe = value.IndexOf('|');
                    var houseId = int.Parse(value.Substring(0, pipe), CultureInfo.InvariantCulture);
                    state.AddPlacedItem(houseId, value.Substring(pipe + 1));
                }
                else if (key == "deco")
                {
                    var parts = value.Split('|');
                    state.AddDecoration(new Decorations.Decoration(
                        parts[1],
                        int.Parse(parts[0], CultureInfo.InvariantCulture),
                        new GridPoint(
                            float.Parse(parts[2], CultureInfo.InvariantCulture),
                            float.Parse(parts[3], CultureInfo.InvariantCulture))));
                }
            }

            return state;
        }
    }
}
