using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Doggiehood.Core.Onboarding;

namespace Doggiehood.Core.World
{
    /// <summary>
    /// Serializes the durable parts of GameState (#27): coin balance and
    /// permanently placed items. A simple line format keeps Core free of
    /// JSON/engine dependencies; the Unity layer decides where the string
    /// lives on disk (local save only — no accounts, no backend).
    /// Active quests are regenerated by the daily rotation rather than
    /// persisted — nothing is lost because quests never expire (#28).
    /// </summary>
    public static class SaveCodec
    {
        private const string Version = "1";

        public static string Save(GameState state)
        {
            var builder = new StringBuilder();
            builder.Append("version=").Append(Version).Append('\n');
            builder.Append("coins=").Append(state.Wallet.Coins.ToString(CultureInfo.InvariantCulture)).Append('\n');
            builder.Append("onboarded=").Append(state.OnboardingComplete ? "1" : "0").Append('\n');

            // #343: how many authored zones have been unlocked. Zones are
            // deterministic (ZoneCatalog), so the count alone rebuilds both
            // Map and UnlockedZones on load — an unlocked zone survives a
            // relaunch instead of resetting each session. Omitted (loads as 0)
            // for a game that has unlocked nothing.
            if (state.UnlockedZones.Count > 0)
            {
                builder.Append("zones=")
                    .Append(state.UnlockedZones.Count.ToString(CultureInfo.InvariantCulture))
                    .Append('\n');
            }

            // #316: the onboarding reward-chain step, so the one-time chain
            // resumes where it left off and is never restarted or re-paid on
            // reload. Stored by name so it survives any future enum reordering.
            builder.Append("rewardChain=").Append(state.RewardChain.CurrentStep.ToString()).Append('\n');

            // #310: the quest-rotation cadence marker. UTC round-trip format
            // ("O") preserves the exact instant and its UTC kind; the line is
            // omitted entirely until the first rotation has run (null marker).
            if (state.LastRotationUtc.HasValue)
            {
                builder.Append("rotatedUtc=")
                    .Append(state.LastRotationUtc.Value.ToUniversalTime()
                        .ToString("O", CultureInfo.InvariantCulture))
                    .Append('\n');
            }

            foreach (var item in state.PlacedItems)
            {
                builder.Append("placed=")
                    .Append(item.HouseId.ToString(CultureInfo.InvariantCulture))
                    .Append('|')
                    .Append(item.ItemName)
                    .Append('\n');
            }

            foreach (var decoration in state.Decorations)
            {
                builder.Append("deco=")
                    .Append(decoration.HouseId.ToString(CultureInfo.InvariantCulture))
                    .Append('|')
                    .Append(decoration.ItemName)
                    .Append('|')
                    .Append(decoration.YardPosition.X.ToString(CultureInfo.InvariantCulture))
                    .Append('|')
                    .Append(decoration.YardPosition.Z.ToString(CultureInfo.InvariantCulture))
                    .Append('\n');
            }

            return builder.ToString();
        }

        public static GameState Load(string saved)
        {
            if (string.IsNullOrEmpty(saved))
            {
                throw new ArgumentException("Nothing to load.", nameof(saved));
            }

            var state = GameState.CreateNew();
            var sawRewardChain = false;

            foreach (var line in saved.Split('\n'))
            {
                var separator = line.IndexOf('=');
                if (separator < 0)
                {
                    continue;
                }

                var key = line.Substring(0, separator);
                var value = line.Substring(separator + 1);

                if (key == "onboarded")
                {
                    if (value == "1")
                    {
                        state.MarkOnboardingComplete();
                    }
                }
                else if (key == "rewardChain")
                {
                    sawRewardChain = true;
                    if (Enum.TryParse(value, out OnboardingRewardStep step))
                    {
                        state.RestoreRewardChainStep(step);
                    }
                }
                else if (key == "rotatedUtc")
                {
                    state.RecordRotationUtc(DateTime.Parse(
                        value, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind));
                }
                else if (key == "zones")
                {
                    state.RestoreUnlockedZoneCount(int.Parse(value, CultureInfo.InvariantCulture));
                }
                else if (key == "coins")
                {
                    var coins = int.Parse(value, CultureInfo.InvariantCulture);
                    if (coins > 0)
                    {
                        state.Wallet.Deposit(coins);
                    }
                }
                else if (key == "placed")
                {
                    var pipe = value.IndexOf('|');
                    var houseId = int.Parse(value.Substring(0, pipe), CultureInfo.InvariantCulture);
                    state.AddPlacedItem(houseId, value.Substring(pipe + 1));
                }
                else if (key == "deco")
                {
                    var parts = value.Split('|');
                    state.AddDecoration(new Decorations.Decoration(
                        parts[1],
                        int.Parse(parts[0], CultureInfo.InvariantCulture),
                        new GridPoint(
                            float.Parse(parts[2], CultureInfo.InvariantCulture),
                            float.Parse(parts[3], CultureInfo.InvariantCulture))));
                }
            }

            // #316 legacy migration: a pre-#316 save that finished onboarding
            // but carries no rewardChain field is a player long past onboarding
            // — treat the guided chain as already complete so it is never
            // re-offered and their rotation is never re-suppressed.
            if (!sawRewardChain && state.OnboardingComplete)
            {
                state.RestoreRewardChainStep(OnboardingRewardStep.Done);
            }

            return state;
        }
    }
}
